def build_matchers(nlp):
    m = Matcher(nlp.vocab)
    d = DependencyMatcher(nlp.vocab)
    # RESULT
    m.add("RES_VERB_CUES", [[{"LOWER":{"IN":["our","these"]}}, {"LOWER":{"IN":["results","findings"]}}, {"LEMMA":{"IN":["show","indicate","demonstrate","reveal","suggest"]}}], [{"LOWER":"we"}, {"LEMMA":{"IN":["show","find","observe","demonstrate","indicate","reveal","report"]}}]])
    m.add("RES_STATS", [[{"LOWER":{"IN":["p","p-value"]}}, {"IS_PUNCT":True,"OP":"?"}, {"LOWER":{"IN":["<","≤","<="]}}, {"LIKE_NUM":True}], [{"LIKE_NUM":True}, {"TEXT":{"REGEX":"%"}}, {"LOWER":{"IN":["increase","decrease","improvement","reduction"]}}], [{"LIKE_NUM":True}, {"TEXT":{"REGEX":"%"}}, {"LOWER":"ci"}], [{"LOWER":{"IN":["odds","hazard"]}}, {"LOWER":"ratio"}], [{"LOWER":{"IN":["rmse","auc","auroc","accuracy","precision","recall","sensitivity","specificity"]}}], [{"LOWER":"compared"}, {"LOWER":"to"}], [{"LOWER":"achieved"}], [{"LOWER":"yielded"}]])
    d.add("RES_WE_VERB", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["show","find","observe","demonstrate","indicate","reveal","suggest","report"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"subj","RIGHT_ATTRS":{"DEP":{"IN":["nsubj","nsubjpass"]},"LOWER":"we"}}]])
    # EXPERIMENT
    m.add("EXP_SURFACE", [[{"LOWER":"we"}, {"LEMMA":{"IN":["conduct","perform","run","carry","implement"]}}], [{"LOWER":"we"}, {"LEMMA":{"IN":["measure","collect","recruit","randomize","enroll","administer"]}}], [{"LOWER":{"IN":["trial","experiment","study"]}}], [{"LOWER":{"IN":["placebo","control","controlled","double-blind","randomized"]}}], [{"TEXT":{"REGEX":"^n\\s*=\\s*\\d+"}}]])
    d.add("EXP_DOBJ", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["conduct","perform","run","carry","measure","use","utilize","apply","calibrate","assemble","administer"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"obj","RIGHT_ATTRS":{"DEP":{"IN":["dobj","obj"]},"LOWER":{"IN":["experiment","experiments","study","trial","measurement","setup","apparatus","assay"]}}}]])
    # TECHNIQUE
    m.add("TEC_SURFACE", [[{"LOWER":{"IN":["using","with","via","through","by"]}}, {"POS":{"IN":["DET","ADJ"]},"OP":"*"}, {"LEMMA":{"IN":["method","technique","protocol","assay","algorithm","pipeline","architecture","classifier","model"]}}], [{"LOWER":{"IN":["pcr","rt-pcr","western","elisa","mass","spectrometry","mrna","rna-seq","immunohistochemistry","random-forest","svm","cox","kaplan-meier"]}}], [{"LOWER":{"IN":["assay","assays","protocol","protocols"]}}]])
    d.add("TEC_USING", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"POS":"VERB"}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"obl","RIGHT_ATTRS":{"DEP":{"IN":["prep","agent"]}, "LOWER":{"IN":["using","with","via","by","through"]}}}]])
    # DATASET
    m.add("DATA_SURFACE", [[{"LOWER":{"IN":["dataset","data","registry","cohort","biobank","database"]}}], [{"LOWER":{"IN":["mimic","mimic-iii","mimic-iv","uk","biobank","eicu","clinicaltrials.gov","tcga","physionet"]}}], [{"LOWER":{"IN":["patients","participants","subjects"]}}], [{"LOWER":"n"}, {"IS_PUNCT":True,"OP":"?"}, {"LOWER":"="}, {"LIKE_NUM":True}], [{"LOWER":"nct"}, {"IS_DIGIT":True,"OP":"+"}]])
    d.add("DATA_SOURCE", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["collect","use","utilize","obtain","source","recruit","enroll","include"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"obj","RIGHT_ATTRS":{"DEP":{"IN":["obj","dobj"]}, "LOWER":{"IN":["data","dataset","datasets","patients","participants","subjects","records","cohort"]}}}]])
    # ANALYSIS
    m.add("ANA_SURFACE", [[{"LOWER":"we"}, {"LEMMA":{"IN":["analyze","analyse","assess","evaluate","model","fit","estimate","adjust","normalize","standardize"]}}], [{"LOWER":{"IN":["regression","logistic","linear","cox","anova","ancova","mixed-effects","multivariate","univariate"]}}], [{"LOWER":{"IN":["kaplan-meier","survival","hazard","odds"]}}], [{"LOWER":{"IN":["significance","multiple","testing","bonferroni","fdr"]}}]])
    d.add("ANA_DEP", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["analyze","analyse","evaluate","assess","model","fit","estimate","adjust"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"obj","RIGHT_ATTRS":{"DEP":{"IN":["obj","dobj","obl"]}}}]])
    # HYPOTHESIS
    m.add("HYP_SURFACE", [[{"LOWER":{"IN":["we","our"]}}, {"LEMMA":{"IN":["hypothesize","hypothesise","postulate","posit","predict","propose"]}}], [{"LOWER":{"IN":["we","our"]}}, {"LOWER":{"IN":["hypothesis","hypotheses"]}}], [{"LOWER":{"IN":["we","this","the"]}}, {"LOWER":"study","OP":"?"}, {"LEMMA":{"IN":["aim","seek"]}}, {"LOWER":"to"}], [{"LOWER":{"IN":["we"]}}, {"LEMMA":{"IN":["expect"]}}, {"LOWER":"that"}]])
    d.add("HYP_THAT", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["hypothesize","postulate","posit","predict","propose","expect"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"comp","RIGHT_ATTRS":{"DEP":{"IN":["ccomp","xcomp","advcl"]}}}]])
    # INPUT FACT
    m.add("INF_SURFACE", [[{"LOWER":{"IN":["according","given","based"]}}, {"LOWER":"on","OP":"?"}], [{"LOWER":{"IN":["it","this"]}}, {"LEMMA":{"IN":["be"]}}, {"LOWER":{"IN":["known","established","well-known"]}}], [{"LOWER":{"IN":["prior","previous","existing"]}}, {"LOWER":{"IN":["work","evidence","studies","literature"]}}], [{"LOWER":{"IN":["guidelines","consensus","recommendations"]}}], [{"LOWER":{"IN":["baseline","assumption","assumptions","inclusion","exclusion","criteria"]}}]])
    d.add("INF_CITATION", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["report","show","demonstrate"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"obl","RIGHT_ATTRS":{"LOWER":{"IN":["previously","earlier"]}}}]])
    # CONCLUSION
    m.add("CONC_SURFACE", [[{"LOWER":{"IN":["in","overall"]}}, {"LOWER":"conclusion","OP":"?"}], [{"LOWER":{"IN":["in","overall"]}}, {"LOWER":"summary"}], [{"LOWER":{"IN":["we"]}}, {"LEMMA":{"IN":["conclude","confirm"]}}], [{"LOWER":{"IN":["these","our","the"]}}, {"LOWER":{"IN":["findings","results","data"]}}, {"LEMMA":{"IN":["support","suggest","highlight","underscore"]}}], [{"LOWER":{"IN":["implications","clinical","practice","translation","future"]}}]])
    d.add("CONC_DEP", [[{"RIGHT_ID":"v","RIGHT_ATTRS":{"LEMMA":{"IN":["conclude","suggest","support","confirm","highlight","underscore"]}}}, {"LEFT_ID":"v","REL_OP":">>","RIGHT_ID":"subj","RIGHT_ATTRS":{"DEP":{"IN":["nsubj","nsubjpass"]}}}]])
    return m, d
